// AUTO-GENERATED by scripts/stamp-build.js on each build:prod — do not edit by hand.
// Date the pages were last regenerated and codes re-verified from discounts.json.
export const BUILD_DATE_ISO = '2026-08-28';
