import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class AffiliateLinkService {

  private affiliateLinks: { [key: string]: string } = {
    'bylashbabe': 'https://bylashbabe.com?sca_ref=3638091.TQRuyJNRG1',
    'myproteinnl': 'https://tidd.ly/3Dvhdyg',
    'smartphonehoesjes.nl': 'https://tidd.ly/3FRwREQ',
    'veromoda': 'https://www.stylink.it/AdZbXhpwmw',
    'ginatricot': 'https://www.stylink.it/ryMdpCQqA3q',
    'hunkemoller': 'https://tidd.ly/4j17AXp',
    'thuisbezorgd': 'https://tidd.ly/4jpALTJ',
    'footlocker': 'https://tidd.ly/3G2Kxgs',
    'ninjakitchen': 'https://tidd.ly/42pkFTr',
    'samsung': 'https://tidd.ly/42Jik72',
    'yesstyle': 'https://www.yesstyle.com/en/home.html?rco=YESGIRL23&utm_term=YESGIRL23&utm_medium=Influencer&utm_source=dynamic&mcg=influencer',
    'asos': 'https://www.stylink.it/lg3mpUa423',
    'stevemadden': 'https://www.stylink.it/AdZbXh7gYM',
    'lookfantastic': 'https://tidd.ly/4iykJXb',
    'hm': 'https://www.stylink.it/jnNwDTowPY',
    'h&m': 'https://www.stylink.it/jnNwDTowPY',
    'bodyandfit.com': 'https://tidd.ly/3Rbf9yz',
    'westwing': 'https://www.stylink.it/ZqG7gSdn0q',
    'idealofsweden': 'https://www.idealofsweden.eu/?utm_medium=brand-ambassador&ref=bb-m47m59',
    'aliexpress': 'https://tidd.ly/44qRvWs',
    'adidas': 'https://tidd.ly/4iTlN7Q',
    'only': 'https://www.stylink.it/5xZndfMoYe',
    'nike': 'https://www.stylink.it/vR0jnhYnlR',
    'prozis': 'https://prozis.com/NfHG',
    'stylevana': 'https://tidd.ly/4dsPX0F',
    'temu': 'https://temu.to/m/u0p32ew176i',
    'easytoys': 'https://tidd.ly/4ntIXoT',
    'iciparisxl': 'https://tidd.ly/4lMFsJA',
    'yehwang_wholesale': 'https://bit.ly/43fOjKa',
    'desenio': 'https://desen.io/?ref=bb-m47m59',
    'ullapopken.nl': 'https://tidd.ly/4mmCMCH',
    'maletasgreenwich': 'https://tidd.ly/4lPQy0v',
    'voghion': 'https://tidd.ly/3Ep876s',
    'shirttuning.nl': 'https://tidd.ly/4lAMjp6',
    'street-one.nl': 'https://tidd.ly/44fnr0c',
    'zooplus.nl': 'https://tidd.ly/44NnZKP',
    'cecil.nl': 'https://tidd.ly/3Sb7l06',
    'stradivarius': 'https://tidd.ly/3YTQORZ',
    'greetz.nl': 'https://tidd.ly/42NSCOV',
    'albelli': 'https://tidd.ly/4ms3olS',
    'otrium': 'https://tidd.ly/3FpcLSm',
    'zelesta.nl': 'https://tidd.ly/4dyxrUU',
    'smartphoto.nl': 'https://www.smartphoto.nl/foto_tt?tt=4903_12_448474_&r=%2F',
    'secretsales.nl': 'https://tidd.ly/43Atcoa',
    'keepitsneaker': 'https://tidd.ly/4deFHcA',
    'fashionette': 'https://tidd.ly/4j3pE2h',
    'vidaxl': 'https://tidd.ly/42PSPRQ',
    'charlottetilbury': 'https://shop.charlottetilbury.com/or/camref:1110lNBf/[p_id:1110l734]/destination:https%3A%2F%2Fwww.charlottetilbury.com%2Fnl',
    'boohoo': 'https://tidd.ly/3ZsqrTt',
    'boohooman': 'https://tidd.ly/3GZs30J',
    'sansbeaute': 'https://tidd.ly/3EZGXUh',
    'bstn.com': 'https://tidd.ly/3FgECUP',
    'sharkclean.nl': 'https://tidd.ly/4dp8Dyx',
    'prenatal': 'https://tidd.ly/43lmYHH',
    'wish.com': 'https://click.linksynergy.com/deeplink?id=q0MVTK*mZVE&mid=53194&murl=https%3A%2F%2Fwww.wish.com%2Fnl',
    'mvolo.nl': 'https://tidd.ly/3H0Mw5m',
    'bulk.com': 'https://tidd.ly/43rbsdJ',
    'spacenk.com': 'https://tidd.ly/4dFlWeo',
    'naduvi.nl': 'https://tidd.ly/3HnUdT9',
    'kitchenaid': 'https://tidd.ly/4dwNti2',
    'malelions': 'https://tidd.ly/3Z1dr7b',
    'fotocadeau.nl': 'https://tidd.ly/3Z1dIXL',
    '123jaloezie.nl': 'https://tidd.ly/3SR4dqy',
    'upfront': 'https://tidd.ly/4nfNOdh',
    'lounge by zalando': 'https://tidd.ly/3ZknIvm',
    'jhpfashion.nl': 'https://tidd.ly/4kaBWGU',
    'picnic': 'https://tidd.ly/4jkKLxg',
    'amazon': 'https://amzn.to/4lyoE8A',
    'tefal': 'https://tidd.ly/44tjrJB',
    'tennis-point.nl': 'https://tidd.ly/4kB6hPn',
    'lampenlicht.nl': 'https://tidd.ly/3Tlo5m2',
    'earkings.nl': 'https://tidd.ly/3UjR75T',
    'large.nl': 'https://tidd.ly/3TiNQ6E',
    'cashbackxl': 'https://www.cashbackxl.nl?share=wouter-c9c3bf',
    'dyson': 'https://tidd.ly/4dloiic',
    'coolblue': 'https://tidd.ly/3GSohGZ',
    'douglas': 'https://tidd.ly/4ldZ0VD',
    'shein': 'https://www.awin1.com/cread.php?awinmid=18055&awinaffid=1870794&ued=https%3A%2F%2Fnl.shein.com%2F',
    'emmasleepnl': 'https://tidd.ly/47ACnr9',
    'ugg': 'https://tidd.ly/4lw3s2q',
    'jeanscentre.nl': 'https://tidd.ly/3GmmSIe',
    'pearle': 'https://tidd.ly/44oWOpz',
    'converse': 'https://tidd.ly/4jEbhCy',
    'skateshop': 'https://clk.tradedoubler.com/click?p=376362&a=3427761&url=https%3A%2F%2Fwww.skateshop.be%2Fnl%2F',
    'purenaturegoods': 'https://tidd.ly/3FaGtdY',
    'stekkies': 'https://in.stekkies.com/t/t?a=1962471956&as=1971143404&t=2&tk=1',
    'lycamobile': 'https://clk.tradedoubler.com/click?p=335732&a=3427761&url=https%3A%2F%2Fwww.lycamobile.nl%2Fnl%2F%3Fsrsltid%3DAfmBOooraQEWMEo01s4s6rdU6wIjdzSKc_WeseYPUlJv7Ukv-RcyQxEW',
    'fotogeschenk': 'https://www.fotogeschenk.nl/foto/?tt=642_12_448474_&r=%2F',
    'basalbasics.nl': 'https://clk.tradedoubler.com/click?p=345870&a=3427761&url=https%3A%2F%2Fwww.basalbasics.nl%2F',
    'hairworldshop.nl': 'https://clk.tradedoubler.com/click?p=358618&a=3427761&url=https%3A%2F%2Fwww.hairworldshop.nl%2F',
    'vitamine.shop': 'https://clk.tradedoubler.com/click?p=315858&a=3427761&url=https%3A%2F%2Fvitamine.shop%2F',
    'mimmti.com': 'https://tc.tradetracker.net/?c=30770&m=12&a=448474&r=&u=%2F',
    'acrylfoto.nl': 'https://www.acrylfoto.nl/foto/?tt=3380_12_448474_&r=%2F',
    'namly.nl': 'https://clk.tradedoubler.com/click?p=379967&a=3427761&url=https%3A%2F%2Fwww.namly.nl%2F',
    'sixt': 'https://tidd.ly/3H8Oz7y',
    'iphone-cases.nl': 'https://tidd.ly/44LjD74',
    'tuinmeubelshop.nl': 'https://tidd.ly/4mlk526',
    'jadedlondon': 'https://tidd.ly/44NF2MZ',
    'muchachomalo': 'https://tidd.ly/3YYwvDa',
    'parfumdreams.nl': 'https://tidd.ly/43nW6GR',
    'melanojewelry': 'https://tidd.ly/4mMtHU3',
    'dryze.nl': 'https://tidd.ly/4kc4WPj',
    'odido zakelijk': 'https://tidd.ly/3H2v7t8',
    'odido thuis': 'https://tidd.ly/4mtzOwf',
    'odido mobiel': 'https://tidd.ly/45nqt2M',
    'vitaepro.nl': 'https://tidd.ly/4ki4LRI',
    'action': 'https://tidd.ly/4nxwoZW',
    'bluetomato': 'https://tidd.ly/4ldkSBs',
    'schuurman schoenen': 'https://tidd.ly/3ZXRHtp',
    '50plusmobiel': 'https://tidd.ly/3TNztXZ',
    'lucovitaal': 'https://tidd.ly/4l8jxfd',
    'guess': 'https://tidd.ly/3I55PuV',
    'happy-size.nl': 'https://tidd.ly/3VAKX1Y',
    'koreanskincare': 'https://tidd.ly/4peUaus',
    'wildrefill': 'https://tidd.ly/4mUIifD',
    'tenways': 'https://tidd.ly/42mKnsj',
  };

  constructor() { }

  public getAffiliateLink(company: string): string | undefined {
    if(company.includes('(') && !company.includes('(gratis')) {
      var parts = company.split('(');
      company = parts[0].trim();
    }

    return this.affiliateLinks[company];
  }
}
