const fs = require('fs');
const path = require('path');

// routes-extractor.js
//
// Generates three build artifacts from the source of truth:
//   1. routes.txt          — every URL that must be prerendered
//   2. src/sitemap.xml      — the indexable URL set
//   3. brand-content/v2-content-slugs.ts — the router guard's allowlist of shops
//      served by v2 (auto-generated; replaces the old hand-maintained live-v2-slugs.ts)
//
// KEY POLICY: a page exists if, and only if, it has an entry in discounts.json.
//
// This used to be a three-way union (discounts ∪ v1 seo-content ∪ v2 brand-content),
// because a shop whose codes had been pruned still needed to keep its page — its code
// came from a fallback applied inside the component, which discounts.json never saw.
// fetch-discounts.js now injects those backup codes into discounts.json itself, so every
// content page has an entry there by construction and the union collapses to its first
// term. fetch-discounts.js fails the build if that ever stops being true, so this script
// can trust discounts.json completely.
//
// v2 brand-content is still read here — but only to answer a different question: WHICH
// COMPONENT renders a slug (v2 vs v1), not whether the page exists.
//
// The old /v2/{slug} noindexed "preview" tier is retired: there is no allowlist
// anymore, so every shop with v2 content is live v2 on its real /{slug} route.

const ROOT = path.join(__dirname, '..');
const discountsPath = path.join(ROOT, 'src/app/data/discounts.json');
const v2DataDir = path.join(ROOT, 'src/app/company-codes-v2/brand-content/data');
const manifestPath = path.join(ROOT, 'src/app/company-codes-v2/brand-content/v2-content-slugs.ts');

// =========================
// 1. Collect slugs
// =========================

// --- discounts.json: every shop with a page, and its codes (live or backup) ---
const discountSlugs = new Set();
for (const line of JSON.parse(fs.readFileSync(discountsPath, 'utf8'))) {
  if (typeof line !== 'string' || !line.includes(',')) continue;
  const slug = line.split(',')[0].replace(/\([^)]*\)/g, '').trim();
  if (slug) discountSlugs.add(slug);
}

// --- v2 brand-content: the filename IS the slug (server loader reads `${slug}.json`). ---
const v2Slugs = new Set(
  fs.existsSync(v2DataDir)
    ? fs.readdirSync(v2DataDir).filter(f => f.endsWith('.json')).map(f => f.replace(/\.json$/, ''))
    : []
);

// =========================
// 2. Emit the v2-content manifest the router guard reads
// =========================
// The guard runs in the browser bundle and must stay plain strings (it must NOT
// pull the content loader client-side). So we bake the list of v2-content slugs
// into a tiny generated module. This is the single source of truth for "serve v2
// on /:company"; every other shop falls through to the v1 component.
const sortedV2 = Array.from(v2Slugs).sort((a, b) => a.localeCompare(b));
const manifest = `// AUTO-GENERATED by scripts/fill-routes.js — DO NOT EDIT BY HAND.
// One entry per shop that has a v2 brand-content data file. A slug listed here is
// served by CompanyCodesV2Component on the real /:company route (indexed); every
// other shop falls through to the v1 CompanyCodesComponent. Regenerated on every
// prod build, so adding a data file is all it takes to take a shop live on v2.
export const V2_CONTENT_SLUGS: ReadonlySet<string> = new Set([
${sortedV2.map(s => `  '${s.replace(/'/g, "\\'")}',`).join('\n')}
]);

export function hasV2ContentSlug(slug: string | undefined | null): boolean {
  return !!slug && V2_CONTENT_SLUGS.has(slug.toLowerCase());
}
`;
fs.writeFileSync(manifestPath, manifest, 'utf8');

// =========================
// 3. routes.txt — every shop in discounts.json + the utility pages
// =========================
// The blog: the index plus one entry per article. Written out once and reused
// for routes.txt AND the sitemap below — two separate hand-kept copies is how
// /blogs/uniqlo ended up never prerendered (serving the homepage <title>) while
// every article was missing from the sitemap. Add a new article to this one list
// and it gets both.
const blogRoutes = ['blogs', 'blogs/space-nk', 'blogs/lookfantastic', 'blogs/uniqlo'];

// discoverRoutes is false, so a route missing from routes.txt is never
// prerendered and the host falls back to the generic index.html.
const utilityRoutes = ['winkels', 'contact', 'top5', 'privacy-policy', 'blackfriday', 'beste-bonus', 'prikbord', ...blogRoutes, 'code-delen', ''];

const sortedPages = Array.from(discountSlugs).sort((a, b) => a.localeCompare(b));

const allRoutes = new Set([
  ...utilityRoutes.map(r => (r === '' ? '/' : `/${r}`)),
  ...sortedPages.map(s => `/${s}`),
]);
const routesTxt = Array.from(allRoutes).sort((a, b) => a.localeCompare(b)).join('\n');
fs.writeFileSync(path.join(ROOT, 'routes.txt'), routesTxt, 'utf8');

console.log(`routes.txt generated: ${sortedPages.length} shop pages, ${sortedV2.length} on v2.`);

// =========================
// 4. sitemap.xml — the INDEXABLE set
// =========================
// Every shop in discounts.json shows a code — live, or the backup code that
// fetch-discounts.js injected — so the whole set is safe to index.
const BASE_URL = 'https://diski.nl';
const today = new Date().toISOString().split('T')[0];

// ...blogRoutes, not a bare 'blogs': the index page alone used to be listed here,
// so the articles were prerendered but never submitted for indexing.
const sitemapUtility = new Set(['winkels', 'contact', 'top5', 'privacy-policy', ...blogRoutes, 'prikbord', 'blackfriday', 'beste-bonus', 'code-delen', '']);
const sitemapSlugs = Array.from(new Set([...discountSlugs, ...sitemapUtility])).sort((a, b) => a.localeCompare(b));

const urls = sitemapSlugs.map((route) => {
  const pathPart = route === '' ? '/' : `/${route}/`;
  const isHome = route === '';
  const isUtility = sitemapUtility.has(route);
  const priority = isHome ? '1.0' : isUtility ? '0.6' : '0.8';
  const changefreq = isHome ? 'daily' : isUtility ? 'monthly' : 'weekly';
  return `
  <url>
    <loc>${escapeXml(BASE_URL + pathPart)}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}).join('');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;

fs.writeFileSync(path.join(ROOT, 'src/sitemap.xml'), sitemap, 'utf8');
console.log(`sitemap.xml generated: ${sitemapSlugs.length} indexable URLs.`);

function escapeXml(str) {
  return str.replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');
}
