const fs = require('fs');
const path = require('path');

// routes-extractor.js
//
// Generates three build artifacts from the source of truth:
//   1. routes.txt          — every URL that must be prerendered
//   2. src/sitemap.xml      — the indexable URL set
//   3. brand-content/v2-content-slugs.ts — the router guard's allowlist of shops
//      served by v2 (auto-generated; replaces the old hand-maintained live-v2-slugs.ts)
//
// KEY POLICY (changed 2026-07-05): a detail page's existence is driven by CONTENT,
// not by discounts.json. A shop keeps its prerendered /{slug} page as long as it
// has v1 seo-content OR v2 brand-content — even after its codes are pruned from
// discounts.json. discounts.json now only contributes the "code-only" shops that
// have no editorial content. The route universe is therefore the UNION:
//
//     discounts.json slugs  ∪  v1 seo-content slugs  ∪  v2 brand-content slugs
//
// The old /v2/{slug} noindexed "preview" tier is retired: there is no allowlist
// anymore, so every shop with v2 content is live v2 on its real /{slug} route.

const ROOT = path.join(__dirname, '..');
const discountsPath = path.join(ROOT, 'src/app/data/discounts.json');
const v1IndexPath = path.join(ROOT, 'src/app/company-codes/company-seo-content/index.ts');
const v2DataDir = path.join(ROOT, 'src/app/company-codes-v2/brand-content/data');
const manifestPath = path.join(ROOT, 'src/app/company-codes-v2/brand-content/v2-content-slugs.ts');

// =========================
// 1. Collect slugs from every source
// =========================

// --- discounts.json: shops that currently have at least one live code ---
const discountSlugs = new Set();
for (const line of JSON.parse(fs.readFileSync(discountsPath, 'utf8'))) {
  if (typeof line !== 'string' || !line.includes(',')) continue;
  const slug = line.split(',')[0].replace(/\([^)]*\)/g, '').trim();
  if (slug) discountSlugs.add(slug);
}

// --- v1 seo-content: the AUTHORITATIVE slug is the switch label in index.ts, not
//     the filename (e.g. `case 'about you'` -> ./about-you, `case 'h&m'` -> ./h-m). ---
const v1Slugs = new Set();
if (fs.existsSync(v1IndexPath)) {
  const idx = fs.readFileSync(v1IndexPath, 'utf8');
  for (const m of idx.matchAll(/case\s+'([^']+)':/g)) v1Slugs.add(m[1]);
}

// --- v2 brand-content: the filename IS the slug (server loader reads `${slug}.json`). ---
const v2Slugs = new Set(
  fs.existsSync(v2DataDir)
    ? fs.readdirSync(v2DataDir).filter(f => f.endsWith('.json')).map(f => f.replace(/\.json$/, ''))
    : []
);

// =========================
// 2. Emit the v2-content manifest the router guard reads
// =========================
// The guard runs in the browser bundle and must stay plain strings (it must NOT
// pull the content loader client-side). So we bake the list of v2-content slugs
// into a tiny generated module. This is the single source of truth for "serve v2
// on /:company"; every other shop falls through to the v1 component.
const sortedV2 = Array.from(v2Slugs).sort((a, b) => a.localeCompare(b));
const manifest = `// AUTO-GENERATED by scripts/fill-routes.js — DO NOT EDIT BY HAND.
// One entry per shop that has a v2 brand-content data file. A slug listed here is
// served by CompanyCodesV2Component on the real /:company route (indexed); every
// other shop falls through to the v1 CompanyCodesComponent. Regenerated on every
// prod build, so adding a data file is all it takes to take a shop live on v2.
export const V2_CONTENT_SLUGS: ReadonlySet<string> = new Set([
${sortedV2.map(s => `  '${s.replace(/'/g, "\\'")}',`).join('\n')}
]);

export function hasV2ContentSlug(slug: string | undefined | null): boolean {
  return !!slug && V2_CONTENT_SLUGS.has(slug.toLowerCase());
}
`;
fs.writeFileSync(manifestPath, manifest, 'utf8');

// =========================
// 3. routes.txt — prerender the UNION of all page sources + the utility pages
// =========================
const utilityRoutes = ['winkels', 'contact', 'top5', 'privacy-policy', 'blackfriday', 'prikbord', 'blogs', 'blogs/space-nk', 'blogs/lookfantastic', 'code-delen', ''];

const pageSlugs = new Set([...discountSlugs, ...v1Slugs, ...v2Slugs]);
const sortedPages = Array.from(pageSlugs).sort((a, b) => a.localeCompare(b));

const allRoutes = new Set([
  ...utilityRoutes.map(r => (r === '' ? '/' : `/${r}`)),
  ...sortedPages.map(s => `/${s}`),
]);
const routesTxt = Array.from(allRoutes).sort((a, b) => a.localeCompare(b)).join('\n');
fs.writeFileSync(path.join(ROOT, 'routes.txt'), routesTxt, 'utf8');

const contentOnly = sortedPages.filter(s => !discountSlugs.has(s)).length;
console.log(
  `routes.txt generated: ${sortedPages.length} shop pages ` +
  `(${discountSlugs.size} from discounts, ${contentOnly} content-only kept online), ` +
  `${sortedV2.length} on v2.`
);

// =========================
// 4. sitemap.xml — the INDEXABLE set
// =========================
// Indexable set = shops that always show a code + utility pages.
//   - discounts.json slugs: have a live code.
//   - v2 content slugs: every v2 data file carries a `backupCode` (filled by the
//     engine's enrich_backup_codes.py), so a v2 page always renders a code even
//     with no live code — safe to index.
// Still EXCLUDED: v1-only content slugs with no live code. The v1 template gates
// its whole body behind `discountCodes.length > 0`, so those pages are thin
// soft-404 shells until v1 gets its own backup-code handling — don't index them.
const BASE_URL = 'https://diski.nl';
const today = new Date().toISOString().split('T')[0];

const sitemapUtility = new Set(['winkels', 'contact', 'top5', 'privacy-policy', 'blogs', 'prikbord', 'blackfriday', 'code-delen', '']);
const sitemapSlugs = Array.from(new Set([...discountSlugs, ...v2Slugs, ...sitemapUtility])).sort((a, b) => a.localeCompare(b));

const urls = sitemapSlugs.map((route) => {
  const pathPart = route === '' ? '/' : `/${route}/`;
  const isHome = route === '';
  const isUtility = sitemapUtility.has(route);
  const priority = isHome ? '1.0' : isUtility ? '0.6' : '0.8';
  const changefreq = isHome ? 'daily' : isUtility ? 'monthly' : 'weekly';
  return `
  <url>
    <loc>${escapeXml(BASE_URL + pathPart)}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}).join('');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;

fs.writeFileSync(path.join(ROOT, 'src/sitemap.xml'), sitemap, 'utf8');
console.log(`sitemap.xml generated: ${sitemapSlugs.length} indexable URLs.`);

function escapeXml(str) {
  return str.replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');
}
