// Writes the current date into src/app/build-info.ts so pages can show an
// honest "laatst gecontroleerd op {date}" tied to a REAL event (the build /
// regeneration), not a runtime new Date() that would lie on stale client
// renders and cause SSR/CSR hydration mismatches.
//
// Runs as part of `build:prod` (before `ng build`). A default build-info.ts is
// committed so plain `ng build` / `ng serve` still compile without this step.
const fs = require('fs');
const path = require('path');

const now = new Date();
const iso = now.toISOString().slice(0, 10); // YYYY-MM-DD (UTC; date-only)

const content =
  `// AUTO-GENERATED by scripts/stamp-build.js on each build:prod — do not edit by hand.\n` +
  `// Date the pages were last regenerated and codes re-verified from discounts.json.\n` +
  `export const BUILD_DATE_ISO = '${iso}';\n`;

const outPath = path.join(__dirname, '../src/app/build-info.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log(`build-info.ts stamped with ${iso}`);
