/**
 * Allowlist of shops that v2 serves on the REAL /:company route (indexed,
 * replacing v1 for that shop). Everything else with v2 content stays a
 * noindexed /v2/ preview only.
 *
 * Why an explicit allowlist (and not "any shop with v2 content"):
 *   - This is a real, indexable production change, so going live must be a
 *     deliberate, auditable per-shop decision — a half-finished content file
 *     should never auto-publish and get indexed.
 *   - The "exclude the original 5 pilots" policy is RETIRED: nakdfashion,
 *     ginatricot, gutsgusto, geurwolkje are added here like any shop once their
 *     v2 content is ready. (zalando is the exception — still on v1 for now.)
 *
 * This batch is the 25 generated 2026-06-02 from currently NOT-INDEXED detail
 * pages (see input/CANDIDATES.md) — safe to index because they rank nowhere today.
 *
 * To take another shop live later: add its slug here (and make sure it has a
 * brand-content object + is in routes.txt so it prerenders). To revert a shop
 * to v1: remove it here.
 */
export const LIVE_V2_SLUGS: ReadonlySet<string> = new Set([
  'loopearplugs',
  'cabaulifestyle',
  'siroko',
  'bodylab.nl',
  'yesstyle',
  'charlottetilbury',
  'smartphoto.nl',
  'photowall_sweden',
  'trendcarpet',
  'yehwang_wholesale',
  'moovvmore.nl',
  'wildrefill',
  'legionathletics',
  'florencenails',
  'lampenlicht.nl',
  'thegelexpert',
  'calliegifts',
  'mothersearth',
  'jhpfashion.nl',
  'merodacosmetics',
  'kossonutrition.nl',
  'vitaminfit.eu',
  'twistshakebaby',
  'fittasticsportswear',
  'glutespop.com',
  // Added 2026-06-05: second batch promoted from preview to live (each has a
  // brand-content data file and a discounts.json route entry).
  'fotocadeau.nl',
  'geurwolkje',
  'gymshark',
  'hunkemoller',
  'idealofsweden',
  'lookfantastic',
  'myproteinnl',
  'temu',
  'vitakruid',
  // Added 2026-06-07: third batch promoted to live. Each has a brand-content
  // data file and a discounts.json route entry (verified in routes.txt/sitemap).
  '4shine.nl',
  'aimnsportswear',
  'aj-sports.nl',
  'amanoknitwear',
  'badjasparadijs',
  'bbdebiestraatseweide',
  'biteswelove',
  'boomba',
  'bozasieraden',
  'bslm',
  'bstn.com',
  'cecil',
  'cityfit.reformer',
  'curlsbyiris.nl',
  'deachterstehoef',
  'dedic8apparel',
  'doreandrose',
  'edgardcooper',
  'elinerosinajewelry',
  'fejo_studio',
  'fiquethelabel',
  'freciousslowjuice',
  'gastonluga',
  'greenpan',
  'hippegeboortekaartjes',
  'hollandandbarrett',
  'homefitnesscode',
  'ixxi',
  'jackery',
  'jeuliajewelry',
  'jjshouse',
  'kaptenandson',
  'kidsdepartment',
  'kpactive',
  'kymocleaning',
  'lyko',
  'marfum.nl',
  'marleyspoon.nl',
  'mayafreya',
  'mommiesandmiracles',
  'mvolo.nl',
  'mysample.nl',
  'nextextreme',
  'ninjakitchen',
  'nkgellak',
  'nounthestudio',
  'numsy.nl',
  'oliviakate',
  'opberghoekje.nl',
  'organicbasics',
  'osloskinlab',
  'osock_performance',
  'prepmymeal.nl',
  'safira',
  'samiol.com',
  'spacenk.com',
  'sparkleanddream.nl',
  'street-one.nl',
  'stylewe',
  'tefal',
  'thebrandfelice',
  'tommyteleshopping',
  'unwindjewelry',
  'vildthelabel',
  'volero.nl',
  'vulpesbabycare',
  'yvesrocher',
  'zappie',
  'zelesta.nl',
  // Added 2026-06-08: the 7 that initially lacked a discounts.json route, now
  // wired up (data files renamed to match their discounts.json slugs). rowenta
  // resolves via the bracket-stripped "rowenta (X-Force Flex)" entry.
  'aelfriceden',
  'haarshop',
  'loislee',
  'lovelysbyheleen',
  'rowenta',
  'smashedlemon',
  'to-be-dressed.nl',
  // Added 2026-06-10: fourth batch (first 50 not-yet-covered from discounts.json;
  // 3 skipped at gate). Includes pilots nakdfashion/ginatricot/gutsgusto (no longer excluded).
  'nakdfashion',
  'pinkgellac',
  'creamyfabrics',
  'bylashbabe',
  'ginatricot',
  'gutsgusto',
  'hellofresh.nl',
  'desenio',
  'asos',
  'fuelyourbody',
  'bodyandfit.com',
  'shein',
  'mimamsterdam',
  'hugesupplements',
  'sellpy',
  'everyfoods',
  'colorescience',
  'oxknit',
  'dikkedame.com',
  'sunday.nl',
  'upfront',
  'holafly',
  'mydearbeer_nl',
  'famousstore',
  'emmasleepnl',
  '7oclock.de',
  'strengthen.store',
  'morenutrition',
  'kwakzalversports',
  'petree',
  'moisecare',
  'oduree.nl',
  'stichtingsuperchill',
  'welovetheplanet',
  'obelink',
  'vakantieparkdetweebruggen',
  'ezwlz.com',
  'luxuryfragrances.nl',
  'anewsta',
  'flamengolife',
  'loomathelabel.com',
  'begolden',
  'parfumado',
  'dfyne',
  'teveo',
  'dr_blend',
  'icaniwill',

  // Batch generated 2026-06-10 (caption-grounded, next-50 from discounts.json):
  'fitshop.nl',
  'drksonline',
  'silksilky_official',
  'daye',
  'buckedup',
  'brekkybowl.nl',
  'xxlnutrition',
  'on',
  'faume',
  'colourfulrebel',
  'fotofabriek.nl',
  'sunweb',
  'killerbodyfood',
  'hydrojug',
  'bjornborg',
  'aromadiffusing.nl',
  'proglow',
  'seeger',
  'herqsmoments',
  'buitiqo',
  'koro.com',
  'samsung',
  'bikeflip',
  'alpha.lion',
  'little_monkeez.nl',
  'farmcamps',
  'albelli',
  'jbl',
  'stickerbao',
  'merkmeisjeskleding',
  'everdrop',
  'weargalvier',
  'kasteeloost',
  'wavytalkofficial',
  'prozis',
  'maycosmetics.nl',
  'paulaschoice.nl',
  'charmia',
  'armedangels',
  'leentjebymikabaxa',
  'klense.nl',
  'kikomilano',
  'citybeach',
  'framundo',
  'onceuponapp',
  'seductionail',
  'nolimithair.nl',
  'donder',
  'xoxowildhearts',

  // Batch generated 2026-06-11 (caption-grounded + website/reviews tiers, next-50
  // from discounts.json; 4 skipped at gate: puritybase, inokastudio, wellnessrave,
  // dragonpharma_latino). 'cfab' was generated but NOT promoted: it is the same
  // brand as the already-live 'creamyfabrics', so it stays a duplicate and is
  // intentionally left off this allowlist.
  'esn',
  'aybl',
  'youngla',
  'womensbest',
  'terstal',
  'douglas',
  'bubbleroom',
  'cabaia',
  'joybuy',
  'leolive',
  'vvvcadeaukaarten',
  'zazanederland',
  'atmooz.com',
  'stylevana',
  'plutosport',
  'airalo.com',
  'evryjewels',
  'kenwood',
  'littledutch',
  'danielwellington',
  'butternutbox',
  'zumub',
  'dogwithamission',
  'elvou',
  'gympin',
  'zerups',
  'stylekorean',
  'rosalique',
  'wesmyle',
  'imtravell',
  'vanbeton',
  'swimessentials',
  'het_speelatelier',
  'ripsvintage',
  'peintagone_nl',
  'handjevolliefde',
  'ovabalance',
  'aliexpress',
  'seamollybikini',
  'juuniek',
  'amsliving',
  'finelaserclinic',
  'pol3dstudio',
  'sunday.running24',
  'lionheart.fest',
  // --- Batch 2026-06-14: 50 caption-grounded pages from V2_SAFE_CANDIDATES.txt
  // (11 Tier A >=15 captions + 39 Tier B 1-14). Generated by the content engine,
  // schema-validated, ranked by caption coverage.
  'biotechusa',
  'goodevas.com',
  'lakkiegellak',
  'ullapopken.nl',
  'micas',
  'rihoas',
  'gymexclusive.com',
  'safecourtkitchen',
  'loragal',
  '3bearsporridge',
  'easyplants_greenlife',
  'otensien.nl',
  'madlady',
  'olcaygulsenbeauty',
  'pakketpanda',
  'pinnedbyk',
  'rawnutrition',
  'moostwanted',
  'queentarzi',
  'wavenestsurfcamp',
  'ultrahuman_ring',
  'wastoren.nl',
  'zappiebox',
  'iciparisxl',
  'luvmehair',
  'plotpackers',
  'whitefoxboutique',
  'agtronica',
  'goodweigh.nl',
  'nelsonschoenen',
  'oemaayah',
  'tractive',
  'ziettabox',
  'kudlworld',
  'madurodam',
  'momcie',
  'saeroo',
  'zone2club',
  'bybrielshuysje',
  'oace',
  'silkelegancemanon',
  'hivefamilyplanner',
  'msmode',
  'nextory',
  'qthelabel',
  'rectifynutrition',
  'samfriday.com',
  'sportenspelvoordieren.nl',
  'amicicosmetics',
  'bakedoats',
  // --- Batch 2026-06-15: 50 caption-grounded pages from V2_SAFE_CANDIDATES.txt
  // (all Tier B, 1-3 captions; website+reviews-led). Generated by the content engine,
  // schema-validated. (edgy, inokastudio skipped: no resolvable storefront.)
  'garmundo.nl',
  'butlerloftet',
  'buvanha',
  'everready.nl',
  'fithlon',
  'journaway',
  'leopoldvienna',
  'linniesfashion',
  'marathonboard.com',
  'meetmethere',
  'merakitech',
  'minimission.nl',
  'minioliestore',
  'mudmasky.nl',
  'ofm',
  'ommerland',
  'parisactivewear',
  'raboesy',
  'rungne',
  'tadaaz.nl',
  'twinkystore.nl',
  'upway.nl',
  'vitalstyle.nl',
  'wigiwama',
  'albersmodebydaphne',
  'bibiboutique.be',
  'bloominggoodofficial',
  'bucowooncentrum',
  'bydiensilkflowersstyling',
  'deflierefluiter',
  'eeveveofficial',
  'elevatedfashion.eu',
  'emmanoah',
  'evite',
  'familieresortmolenwaard',
  'fatmoose',
  'fit20nl',
  'gymalpha',
  'hanakoko.com',
  'herokacosmetics',
  'homarycom',
  'indya',
  'insentials.supplements',
  'jackysue.official',
  'jeanscentre.nl',
  'jhypes',
  'kaartje2go',
  'kessberlin',
  'laluunbaby',
  'lameremodesty',
]);

export function isLiveV2Slug(slug: string | undefined | null): boolean {
  return !!slug && LIVE_V2_SLUGS.has(slug.toLowerCase());
}
